name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
        run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "22.x"
      - name: Build SASS
        run: pnpm css:build
      - name: Build HTML
        run: pnpm html:build
