name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4
      - name: Install and Build
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "22.x"
        run: |
          pnpm install
          pnpm css:build
          pnpm html:build
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4.6.1